import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>New Tab</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main classname={styles.main}>
        <p>here is some text for the new tab</p>
      </main>
    </div>
  );
}
